name: iconify_flutter_plus
description: '100+ open source icon sets for flutter to make you app more beautiful'
version: 1.0.4
homepage: 'https://github.com/bineshburjamagar/iconify_flutter_plus'

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

